services:
  # Redis Cluster for caching
  redis-1:
    image: redis:7-alpine
    container_name: voice-bot-redis-1
    command: redis-server --port 7001 --cluster-enabled yes --cluster-config-file nodes-1.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7001:7001"
    volumes:
      - redis-1-data:/data
    networks:
      - voice-bot-network
    restart: unless-stopped

  redis-2:
    image: redis:7-alpine
    container_name: voice-bot-redis-2
    command: redis-server --port 7002 --cluster-enabled yes --cluster-config-file nodes-2.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7002:7002"
    volumes:
      - redis-2-data:/data
    networks:
      - voice-bot-network
    restart: unless-stopped

  redis-3:
    image: redis:7-alpine
    container_name: voice-bot-redis-3
    command: redis-server --port 7003 --cluster-enabled yes --cluster-config-file nodes-3.conf --cluster-node-timeout 5000 --appendonly yes
    ports:
      - "7003:7003"
    volumes:
      - redis-3-data:/data
    networks:
      - voice-bot-network
    restart: unless-stopped

  # Redis Cluster Initialization (runs once)
  redis-cluster-init:
    image: redis:7-alpine
    container_name: voice-bot-redis-init
    command: >
      sh -c "
        sleep 10 &&
        redis-cli --cluster create 
        redis-1:7001 redis-2:7002 redis-3:7003 
        --cluster-replicas 0 --cluster-yes
        || echo 'Cluster already initialized'
      "
    depends_on:
      - redis-1
      - redis-2
      - redis-3
    networks:
      - voice-bot-network
    restart: "no"

  prometheus:
    image: prom/prometheus:latest
    container_name: voice-bot-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/rules.yml:/etc/prometheus/rules.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=30d'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.external-url=http://localhost:9090'
    restart: unless-stopped
    networks:
      - voice-bot-network

  grafana:
    image: grafana/grafana:latest
    container_name: voice-bot-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USERNAME=admin
      - GF_SECURITY_ADMIN_PASSWORD=secure_admin_password_2024
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_SECURITY_SECRET_KEY=voice_bot_secret_key_very_long_random_string_2024
      - GF_SECURITY_DISABLE_GRAVATAR=true
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_ANALYTICS_CHECK_FOR_UPDATES=false
      - GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
    restart: unless-stopped
    networks:
      - voice-bot-network
    depends_on:
      - prometheus

  alertmanager:
    image: prom/alertmanager:latest
    container_name: voice-bot-alertmanager
    ports:
      - "9093:9093"
    volumes:
      - ./monitoring/alertmanager.yml:/etc/alertmanager/alertmanager.yml
      - alertmanager-data:/alertmanager
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
      - '--storage.path=/alertmanager'
      - '--web.external-url=http://localhost:9093'
    restart: unless-stopped
    networks:
      - voice-bot-network

  # Optional: Pushgateway for batch jobs
  pushgateway:
    image: prom/pushgateway:latest
    container_name: voice-bot-pushgateway
    ports:
      - "9091:9091"
    restart: unless-stopped
    networks:
      - voice-bot-network

networks:
  voice-bot-network:
    driver: bridge

volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  alertmanager-data:
    driver: local
  redis-1-data:
    driver: local
  redis-2-data:
    driver: local
  redis-3-data:
    driver: local